import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';

const defaultEndpoint = 'https://rickandmortyapi.com/api/character';

export async function getServerSideProps({ query }) {
  const { id } = query;
  const res = await fetch(`${defaultEndpoint}/${id}`);
  const data = await res.json();
  return {
    props: { data },
  };
}

export default function CharacterPage({ data }) {
  console.log('character data', data);

  return (
    <div className={styles.container}>
      <Head>
        <title>page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Wubba Lubba Dub Dub</h1>
      </main>
    </div>
  );
}
